// movie types
export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_NOW_PLAYING_MOVIES_SUCCESS = "GET_NOW_PLAYING_MOVIES_SUCCESS";
export const GET_DAILY_TRENDING_MOVIES_SUCCESS =
  "GET_DAILY_TRENDING_MOVIES_SUCCESS";
export const GET_WEEKLY_TRENDING_MOVIES_SUCCESS =
  "GET_WEEKLY_TRENDING_MOVIES_SUCCESS";

export const GET_POPULAR_MOVIES_LOADING = "GET_POPULAR_MOVIES_LOADING";
export const GET_TOP_RATED_MOVIES_LOADING = "GET_TOP_RATED_MOVIES_LOADING";
export const GET_NOW_PLAYING_MOVIES_LOADING = "GET_NOW_PLAYING_MOVIES_LOADING";
export const GET_DAILY_TRENDING_MOVIES_LOADING =
  "GET_DAILY_TRENDING_MOVIES_LOADING";
export const GET_WEEKLY_TRENDING_MOVIES_LOADING =
  "GET_WEEKLY_TRENDING_MOVIES_LOADING";

export const GET_POPULAR_MOVIES_ERROR = "GET_POPULAR_MOVIES_ERROR";
export const GET_TOP_RATED_MOVIES_ERROR = "GET_TOP_RATED_MOVIES_ERROR";
export const GET_NOW_PLAYING_MOVIES_ERROR = "GET_NOW_PLAYING_MOVIES_ERROR";
export const GET_DAILY_TRENDING_MOVIES_ERROR =
  "GET_DAILY_TRENDING_MOVIES_ERROR";
export const GET_WEEKLY_TRENDING_MOVIES_ERROR =
  "GET_WEEKLY_TRENDING_MOVIES_ERROR";

// tv types
export const GET_POPULAR_TV_SUCCESS = "GET_POPULAR_TV_SUCCESS";
export const GET_TOP_RATED_TV_SUCCESS = "GET_TOP_RATED_TV_SUCCESS";
export const GET_ON_THE_AIR_TV_SUCCESS = "GET_ON_THE_AIR_TV_SUCCESS";
export const GET_DAILY_TRENDING_TV_SUCCESS = "GET_DAILY_TRENDING_TV_SUCCESS";
export const GET_WEEKLY_TRENDING_TV_SUCCESS = "GET_WEEKLY_TRENDING_TV_SUCCESS";

export const GET_POPULAR_TV_LOADING = "GET_POPULAR_TV_LOADING";
export const GET_TOP_RATED_TV_LOADING = "GET_TOP_RATED_TV_LOADING";
export const GET_ON_THE_AIR_TV_LOADING = "GET_ON_THE_AIR_TV_LOADING";
export const GET_DAILY_TRENDING_TV_LOADING = "GET_DAILY_TRENDING_TV_LOADING";
export const GET_WEEKLY_TRENDING_TV_LOADING = "GET_WEEKLY_TRENDING_TV_LOADING";

export const GET_POPULAR_TV_ERROR = "GET_POPULAR_TV_ERROR";
export const GET_TOP_RATED_TV_ERROR = "GET_TOP_RATED_TV_ERROR";
export const GET_ON_THE_AIR_TV_ERROR = "GET_ON_THE_AIR_TV_ERROR";
export const GET_DAILY_TRENDING_TV_ERROR = "GET_DAILY_TRENDING_TV_ERROR";
export const GET_WEEKLY_TRENDING_TV_ERROR = "GET_WEEKLY_TRENDING_TV_ERROR";

// detail types
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_LOADING = "GET_MOVIE_DETAILS_LOADING";
export const GET_MOVIE_DETAILS_ERROR = "GET_MOVIE_DETAILS_ERROR";
export const RESET_MOVIE_DETAILS = "RESET_MOVIE_DETAILS";

export const GET_TV_DETAILS_SUCCESS = "GET_TV_DETAILS_SUCCESS";
export const GET_TV_DETAILS_LOADING = "GET_TV_DETAILS_LOADING";
export const GET_TV_DETAILS_ERROR = "GET_TV_DETAILS_ERROR";
export const RESET_TV_DETAILS = "RESET_MOVIE_DETAILS";

export const GET_PERSON_DETAILS_SUCCESS = "GET_PERSON_DETAILS_SUCCESS";
export const GET_PERSON_DETAILS_LOADING = "GET_PERSON_DETAILS_LOADING";
export const GET_PERSON_DETAILS_ERROR = "GET_PERSON_DETAILS_ERROR";
export const RESET_PERSON_DETAILS = "RESET_MOVIE_DETAILS";
