export const GET_MOVIE_GENRES = "GET_MOVIE_GENRES";
export const GET_TV_GENRES = "GET_TV_GENRES";
export const GET_DAILY_TRENDING_MOVIES = "GET_DAILY_TRENDING_MOVIES";
export const GET_DAILY_TRENDING_TV = "GET_DAILY_TRENDING_TV";
