// movie types
export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_NOW_PLAYING_MOVIES_SUCCESS = "GET_NOW_PLAYING_MOVIES_SUCCESS";
export const GET_DAILY_TRENDING_MOVIES_SUCCESS =
  "GET_DAILY_TRENDING_MOVIES_SUCCESS";
export const GET_WEEKLY_TRENDING_MOVIES_SUCCESS =
  "GET_WEEKLY_TRENDING_MOVIES_SUCCESS";
export const GET_MOVIE_GENRES_SUCCESS = "GET_MOVIE_GENRES_SUCCESS";

export const GET_POPULAR_MOVIES_LOADING = "GET_POPULAR_MOVIES_LOADING";
export const GET_TOP_RATED_MOVIES_LOADING = "GET_TOP_RATED_MOVIES_LOADING";
export const GET_NOW_PLAYING_MOVIES_LOADING = "GET_NOW_PLAYING_MOVIES_LOADING";
export const GET_DAILY_TRENDING_MOVIES_LOADING =
  "GET_DAILY_TRENDING_MOVIES_LOADING";
export const GET_WEEKLY_TRENDING_MOVIES_LOADING =
  "GET_WEEKLY_TRENDING_MOVIES_LOADING";
export const GET_MOVIE_GENRES_LOADING = "GET_MOVIE_GENRES_LOADING";

export const GET_POPULAR_MOVIES_ERROR = "GET_POPULAR_MOVIES_ERROR";
export const GET_TOP_RATED_MOVIES_ERROR = "GET_TOP_RATED_MOVIES_ERROR";
export const GET_NOW_PLAYING_MOVIES_ERROR = "GET_NOW_PLAYING_MOVIES_ERROR";
export const GET_DAILY_TRENDING_MOVIES_ERROR =
  "GET_DAILY_TRENDING_MOVIES_ERROR";
export const GET_WEEKLY_TRENDING_MOVIES_ERROR =
  "GET_WEEKLY_TRENDING_MOVIES_ERROR";
export const GET_MOVIE_GENRES_ERROR = "GET_MOVIE_GENRES_ERROR";

// tv types
export const GET_POPULAR_TV_SUCCESS = "GET_POPULAR_TV_SUCCESS";
export const GET_TOP_RATED_TV_SUCCESS = "GET_TOP_RATED_TV_SUCCESS";
export const GET_ON_THE_AIR_TV_SUCCESS = "GET_ON_THE_AIR_TV_SUCCESS";
export const GET_DAILY_TRENDING_TV_SUCCESS = "GET_DAILY_TRENDING_TV_SUCCESS";
export const GET_WEEKLY_TRENDING_TV_SUCCESS = "GET_WEEKLY_TRENDING_TV_SUCCESS";
export const GET_TV_GENRES_SUCCESS = "GET_TV_GENRES_SUCCESS";

export const GET_POPULAR_TV_LOADING = "GET_POPULAR_TV_LOADING";
export const GET_TOP_RATED_TV_LOADING = "GET_TOP_RATED_TV_LOADING";
export const GET_ON_THE_AIR_TV_LOADING = "GET_ON_THE_AIR_TV_LOADING";
export const GET_DAILY_TRENDING_TV_LOADING = "GET_DAILY_TRENDING_TV_LOADING";
export const GET_WEEKLY_TRENDING_TV_LOADING = "GET_WEEKLY_TRENDING_TV_LOADING";
export const GET_TV_GENRES_LOADING = "GET_TV_GENRES_LOADING";

export const GET_POPULAR_TV_ERROR = "GET_POPULAR_TV_ERROR";
export const GET_TOP_RATED_TV_ERROR = "GET_TOP_RATED_TV_ERROR";
export const GET_ON_THE_AIR_TV_ERROR = "GET_ON_THE_AIR_TV_ERROR";
export const GET_DAILY_TRENDING_TV_ERROR = "GET_DAILY_TRENDING_TV_ERROR";
export const GET_WEEKLY_TRENDING_TV_ERROR = "GET_WEEKLY_TRENDING_TV_ERROR";
export const GET_TV_GENRES_ERROR = "GET_TV_GENRES_ERROR";
